name: Sync All Branches

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0:00 触发一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: CyrusZhou-CN/bevy
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config pull.rebase false  # 配置为 merge 模式

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/bevyengine/bevy.git

      - name: Fetch all branches and tags from upstream
        run: |
          git fetch upstream --tags

      - name: Sync branches
        run: |
          for branch in $(git branch -r | grep 'upstream/' | grep -v '\->' | sed 's/upstream\///'); do
            echo "Processing branch: $branch"
            if git show-ref --verify --quiet "refs/heads/$branch"; then
              git checkout "$branch"
              git reset --hard "upstream/$branch" || echo "Failed to reset branch $branch"
            else
              git checkout -b "$branch" "upstream/$branch"
            fi
            git push origin "$branch" || echo "Failed to push branch $branch"
          done

      - name: Sync tags
        run: |
          for tag in $(git ls-remote --tags upstream | awk '{print $2}' | sed 's/refs\/tags\///'); do
            echo "Processing tag: $tag"
            # Check if the tag already exists locally
            if git show-ref --tags | grep -q "refs/tags/$tag"; then
              git tag -d "$tag" || echo "Failed to delete local tag $tag"
            fi
            # Delete remote tag if it exists
            git push origin :refs/tags/$tag || echo "Failed to delete remote tag $tag"
            # Fetch the tag from upstream and create it
            git fetch upstream tag "$tag"
            git tag "$tag" "upstream/$tag"
            git push origin "$tag" || echo "Failed to push tag $tag"
          done

      - name: Cleanup
        run: |
          git gc --prune=now
