name: Sync All Branches
name: Sync Repos

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0:00 触发一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: CyrusZhou-CN/bevy
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config pull.rebase false  # 配置为 merge 模式

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/bevyengine/bevy.git

      - name: Fetch all branches and tags from upstream
        run: |
          git fetch upstream

      - name: Sync branches
        run: |
          for branch in $(git branch -r | grep 'upstream/' | grep -v '\->' | sed 's/upstream\///'); do
            echo "Processing branch: $branch"
            if git show-ref --verify --quiet "refs/heads/$branch"; then
              git checkout "$branch"
              git pull --no-rebase upstream "$branch"
            else
              git checkout -b "$branch" "upstream/$branch"
            fi
            git push origin "$branch"
          done

      - name: Sync tags
        run: |
          for tag in $(git ls-remote --tags upstream | awk '{print $2}' | sed 's/refs\/tags\///'); do
            echo "Processing tag: $tag"
            if git show-ref --tags | grep -q "refs/tags/$tag"; then
              git fetch upstream tag "$tag"
              git tag -d "$tag"
              git fetch upstream --tags
              git tag "$tag" "upstream/$tag"
            else
              git fetch upstream tag "$tag"
              git tag "$tag" "upstream/$tag"
            fi
            git push origin "$tag"
          done

      - name: Cleanup
        run: |
          git gc --prune=now
